---
- name: Install ClickHouse
  hosts: clickhouse
  become: true
  handlers:
    - name: Start ClickHouse service
      ansible.builtin.service:
        name: clickhouse-server.service
        state: restarted

  tasks:
    - name: Install ClickHouse packages directly from the repository
      ansible.builtin.yum:
        name:
          - "https://packages.clickhouse.com/rpm/stable/clickhouse-client-{{ clickhouse_version }}.noarch.rpm"
          - "https://packages.clickhouse.com/rpm/stable/clickhouse-server-{{ clickhouse_version }}.noarch.rpm"
          - "https://packages.clickhouse.com/rpm/stable/clickhouse-common-static-{{ clickhouse_version }}.x86_64.rpm"
        disable_gpg_check: true

    - name: Reload systemd manager configuration
      ansible.builtin.shell: systemctl daemon-reload

    - name: Ensure ClickHouse service is enabled and started
      ansible.builtin.service:
        name: clickhouse-server
        state: started
        enabled: true

    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc != 82
      changed_when: create_db.rc == 0

- name: Install Vector
  hosts: vector
  tags: vector
  become: true
  handlers:
    - name: Restart Vector service
      ansible.builtin.service:
        name: vector
        state: restarted

  tasks:
    - name: Install Vector package directly from the repository
      ansible.builtin.yum:
        name: "https://yum.vector.dev/stable/vector-0/x86_64/vector-{{ vector_rpm_version }}.x86_64.rpm"
        disable_gpg_check: true

      notify: Restart Vector service

    - name: Replace Vector configuration file
      ansible.builtin.template:
        src: templates/vector.toml.j2
        dest: /etc/vector/vector.yaml
        owner: root
        group: root
        mode: "0644"
      notify: Restart Vector service

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
      
- name: Install nginx
  hosts: lighthouse
  handlers:
    - name: start-nginx
      become: true
      command: nginx
    - name: reload-nginx
      become: true
      command: nginx -s reload
  tasks:
    - name: Install nginx
      become: true
      ansible.builtin.yum:
        name: nginx
        state: present
      notify: start-nginx
    - name: write nginx general config
      become: true
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: 0644
      notify: reload-nginx

- name: Install lighthouse
  hosts: lighthouse
  handlers:
    - name: reload-nginx
      become: true
      command: nginx -s reload
  pre_tasks:
    - name: Lighthouse | install git
      become: true
      ansible.builtin.yum:
        name: git
        state: present
  tasks:
    - name: Lighthouse | git clone
      become: true
      git:
        repo: "{{ lighthouse_git }}"
        version: master
        dest: "{{ lighthouse_dir }}"
    - name: write lighthouse nginx config
      become: true
      ansible.builtin.template:
        src: templates/lighthouse.conf.j2
        dest: /etc/nginx/conf.d/default.conf
        mode: 0644
      notify: reload-nginx